//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xyRESTTestLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xyRESTTestLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All test finished succeed.
        /// </summary>
        internal static string strAllTestFinishedSucceed {
            get {
                return ResourceManager.GetString("strAllTestFinishedSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert Failed: JSON path {jsonPath} vot found in response..
        /// </summary>
        internal static string strAssertFailedJSONPathNotFound {
            get {
                return ResourceManager.GetString("strAssertFailedJSONPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert Failed: Expected value at JSON path &apos;{0}&apos; to be &apos;{1}&apos;, but got &apos;{2}&apos;.
        /// </summary>
        internal static string strAssertFailedJSONValueError {
            get {
                return ResourceManager.GetString("strAssertFailedJSONValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert Failed: Expected content type application/json, but got {0}.
        /// </summary>
        internal static string strAssertFailedNotJSON {
            get {
                return ResourceManager.GetString("strAssertFailedNotJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert Failed: Expected status code {0}, but got &quot;{1}.
        /// </summary>
        internal static string strAssertFailedStatusCode {
            get {
                return ResourceManager.GetString("strAssertFailedStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert Failed: Unknown assert type &apos;{0}&apos;.
        /// </summary>
        internal static string strAssertFailedUnknowType {
            get {
                return ResourceManager.GetString("strAssertFailedUnknowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert: {0}.
        /// </summary>
        internal static string strAssertType {
            get {
                return ResourceManager.GetString("strAssertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when sending request: {0}.
        /// </summary>
        internal static string strErrorWhenSendingRequest_ {
            get {
                return ResourceManager.GetString("strErrorWhenSendingRequest:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Value: {0}.
        /// </summary>
        internal static string strExpectedValue {
            get {
                return ResourceManager.GetString("strExpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... Failed.
        /// </summary>
        internal static string strFailed {
            get {
                return ResourceManager.GetString("strFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Method: {0}.
        /// </summary>
        internal static string strRequestMethod {
            get {
                return ResourceManager.GetString("strRequestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start test....
        /// </summary>
        internal static string strStartTest {
            get {
                return ResourceManager.GetString("strStartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... Succeed.
        /// </summary>
        internal static string strSucceed {
            get {
                return ResourceManager.GetString("strSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target URL: {0}.
        /// </summary>
        internal static string strTargetApi {
            get {
                return ResourceManager.GetString("strTargetApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Case: {0}.
        /// </summary>
        internal static string strTestCaseName {
            get {
                return ResourceManager.GetString("strTestCaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Data: {0}.
        /// </summary>
        internal static string strTestData {
            get {
                return ResourceManager.GetString("strTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time used: {0} seconds.
        /// </summary>
        internal static string strTestTime {
            get {
                return ResourceManager.GetString("strTestTime", resourceCulture);
            }
        }
    }
}
