//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xyRESTTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xyRESTTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap drop_down {
            get {
                object obj = ResourceManager.GetObject("drop_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap New {
            get {
                object obj = ResourceManager.GetObject("New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenFile {
            get {
                object obj = ResourceManager.GetObject("OpenFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Run {
            get {
                object obj = ResourceManager.GetObject("Run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an assertion.
        /// </summary>
        internal static string strAddAssertion {
            get {
                return ResourceManager.GetString("strAddAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a header.
        /// </summary>
        internal static string strAddHeader {
            get {
                return ResourceManager.GetString("strAddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a JSON value.
        /// </summary>
        internal static string strAddJSONValue {
            get {
                return ResourceManager.GetString("strAddJSONValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a parameter.
        /// </summary>
        internal static string strAddParameter {
            get {
                return ResourceManager.GetString("strAddParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a read data item.
        /// </summary>
        internal static string strAddReadItem {
            get {
                return ResourceManager.GetString("strAddReadItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a test case.
        /// </summary>
        internal static string strAddTestCase {
            get {
                return ResourceManager.GetString("strAddTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a test data record.
        /// </summary>
        internal static string strAddTestDataDecord {
            get {
                return ResourceManager.GetString("strAddTestDataDecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REST API Test Tool.
        /// </summary>
        internal static string strAppTitle {
            get {
                return ResourceManager.GetString("strAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Asserts.
        /// </summary>
        internal static string strAssertCount {
            get {
                return ResourceManager.GetString("strAssertCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion Information.
        /// </summary>
        internal static string strAssertionInformation {
            get {
                return ResourceManager.GetString("strAssertionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion List.
        /// </summary>
        internal static string strAssertionList {
            get {
                return ResourceManager.GetString("strAssertionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Type.
        /// </summary>
        internal static string strContentType {
            get {
                return ResourceManager.GetString("strContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Generator.
        /// </summary>
        internal static string strDataGenerator {
            get {
                return ResourceManager.GetString("strDataGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected assertion.
        /// </summary>
        internal static string strDeleteAssertion {
            get {
                return ResourceManager.GetString("strDeleteAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected header.
        /// </summary>
        internal static string strDeleteHeader {
            get {
                return ResourceManager.GetString("strDeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected JSON value.
        /// </summary>
        internal static string strDeleteJSONValue {
            get {
                return ResourceManager.GetString("strDeleteJSONValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected parameter.
        /// </summary>
        internal static string strDeleteParameter {
            get {
                return ResourceManager.GetString("strDeleteParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected read data item.
        /// </summary>
        internal static string strDeleteReadItem {
            get {
                return ResourceManager.GetString("strDeleteReadItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected test case.
        /// </summary>
        internal static string strDeleteTestCase {
            get {
                return ResourceManager.GetString("strDeleteTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected data record.
        /// </summary>
        internal static string strDeleteTestDataRecord {
            get {
                return ResourceManager.GetString("strDeleteTestDataRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to edit.
        /// </summary>
        internal static string strDoubleClickToEdit {
            get {
                return ResourceManager.GetString("strDoubleClickToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamically generate test case.
        /// </summary>
        internal static string strDynamicallyGenerateTestCase {
            get {
                return ResourceManager.GetString("strDynamicallyGenerateTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected value.
        /// </summary>
        internal static string strExpectedValue {
            get {
                return ResourceManager.GetString("strExpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Already Added.
        /// </summary>
        internal static string strFileAlreadyAdded {
            get {
                return ResourceManager.GetString("strFileAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Data Already Added.
        /// </summary>
        internal static string strFormDataAlreadyAdded {
            get {
                return ResourceManager.GetString("strFormDataAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Path.
        /// </summary>
        internal static string strJSONPath {
            get {
                return ResourceManager.GetString("strJSONPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string strKey {
            get {
                return ResourceManager.GetString("strKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Name:.
        /// </summary>
        internal static string strLbUploadFileKeyName {
            get {
                return ResourceManager.GetString("strLbUploadFileKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        internal static string strLoadProjectFlashInfo {
            get {
                return ResourceManager.GetString("strLoadProjectFlashInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name.
        /// </summary>
        internal static string strLoginName {
            get {
                return ResourceManager.GetString("strLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Case Parameter.
        /// </summary>
        internal static string strMenuInsertCaseParameter {
            get {
                return ResourceManager.GetString("strMenuInsertCaseParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Project Parameter.
        /// </summary>
        internal static string strMenuInsertProjectParameter {
            get {
                return ResourceManager.GetString("strMenuInsertProjectParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name:.
        /// </summary>
        internal static string strNewProjectName {
            get {
                return ResourceManager.GetString("strNewProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Save Folder:.
        /// </summary>
        internal static string strNewProjectSaveFolder {
            get {
                return ResourceManager.GetString("strNewProjectSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Save Name:.
        /// </summary>
        internal static string strNewProjectSaveName {
            get {
                return ResourceManager.GetString("strNewProjectSaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New test project.
        /// </summary>
        internal static string strNewTestProject {
            get {
                return ResourceManager.GetString("strNewTestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Project Loaded.
        /// </summary>
        internal static string strNoProjectLoaded {
            get {
                return ResourceManager.GetString("strNoProjectLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string strOk {
            get {
                return ResourceManager.GetString("strOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a test project.
        /// </summary>
        internal static string strOpenTestProject {
            get {
                return ResourceManager.GetString("strOpenTestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Name.
        /// </summary>
        internal static string strParameterName {
            get {
                return ResourceManager.GetString("strParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string strParameters {
            get {
                return ResourceManager.GetString("strParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Parameter Selector.
        /// </summary>
        internal static string strParameterSelectorTitle_Case {
            get {
                return ResourceManager.GetString("strParameterSelectorTitle_Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Parameter Selector.
        /// </summary>
        internal static string strParameterSelectorTitle_Project {
            get {
                return ResourceManager.GetString("strParameterSelectorTitle_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string strPassword {
            get {
                return ResourceManager.GetString("strPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Could not read file from disk. Original error: {0}.
        /// </summary>
        internal static string strProjectOpenError {
            get {
                return ResourceManager.GetString("strProjectOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} read data items.
        /// </summary>
        internal static string strReadDataCount {
            get {
                return ResourceManager.GetString("strReadDataCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Data List.
        /// </summary>
        internal static string strReadDataList {
            get {
                return ResourceManager.GetString("strReadDataList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Information.
        /// </summary>
        internal static string strRequestInformation {
            get {
                return ResourceManager.GetString("strRequestInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished..
        /// </summary>
        internal static string strRunFinished {
            get {
                return ResourceManager.GetString("strRunFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running....
        /// </summary>
        internal static string strRunning {
            get {
                return ResourceManager.GetString("strRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run whole test project.
        /// </summary>
        internal static string strRunTestProject {
            get {
                return ResourceManager.GetString("strRunTestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run this test case.
        /// </summary>
        internal static string strRunThisTestCase {
            get {
                return ResourceManager.GetString("strRunThisTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set test data file: {0}.
        /// </summary>
        internal static string strSetTestDataFile {
            get {
                return ResourceManager.GetString("strSetTestDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Data Records.
        /// </summary>
        internal static string strTestDataRecords {
            get {
                return ResourceManager.GetString("strTestDataRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add one upload file.
        /// </summary>
        internal static string strTsbAddFile {
            get {
                return ResourceManager.GetString("strTsbAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add one form data.
        /// </summary>
        internal static string strTsbAddFormData {
            get {
                return ResourceManager.GetString("strTsbAddFormData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected upload file.
        /// </summary>
        internal static string strTsbDelFile {
            get {
                return ResourceManager.GetString("strTsbDelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected form data.
        /// </summary>
        internal static string strTsbDelFormData {
            get {
                return ResourceManager.GetString("strTsbDelFormData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        internal static string strTslFiles {
            get {
                return ResourceManager.GetString("strTslFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Datas.
        /// </summary>
        internal static string strTslFormData {
            get {
                return ResourceManager.GetString("strTslFormData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unfefined&gt;.
        /// </summary>
        internal static string strUnfefined {
            get {
                return ResourceManager.GetString("strUnfefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string strValue {
            get {
                return ResourceManager.GetString("strValue", resourceCulture);
            }
        }
    }
}
